### ISSUE TITLE
Open Peek definition (Alt+F12) window with white background and orange font

### ISSUE THREAD

**Issue by vborodaev** [TomGUN02/Ayu-TrueMirage#1]
When ures press Alt+F12, a peek definition window appears with a white background and light font.
![image](https://user-images.githubusercontent.com/43146212/147493020-a6e117d4-9687-4874-b18e-a0529c5caeb6.png)
It would be very nice if somebody could fix this problem.

**Comment by TomGUN02** [comment]
> 



> When ures press Alt+F12, a peek definition window appears with a white background and light font. ![image](https://user-images.githubusercontent.com/43146212/147493020-a6e117d4-9687-4874-b18e-a0529c5caeb6.png) It would be very nice if somebody could fix this problem.

Thanks its fixed now!
